from __future__ import annotations

from pathlib import Path


OUTPUT = Path("info-card.svg")

# ── Curated profile data (edit these to personalize) ─────────────────────
USERNAME = "om0701"
LINES: list[tuple[str, str]] = [
    ("OS", "Windows 11 / Ubuntu"),
    ("Host", "Earth"),
    ("Shell", "PowerShell / Bash"),
    ("Editor", "VS Code"),
    ("Languages", "Python · TypeScript · Go · C++"),
    ("Frameworks", "React · Next.js · FastAPI · Flask"),
    ("Interests", "AI/ML · Automation · Open Source"),
    ("Contact", f"github.com/{USERNAME}"),
]


def build_svg() -> str:
    card_width = 760
    card_height = 420
    left = 32
    top = 55

    body = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {card_width} {card_height}" width="{card_width}" height="{card_height}">',
        '<rect width="100%" height="100%" fill="#0a0a0a" rx="14"/>',
        '<rect x="12" y="12" width="736" height="396" rx="10" fill="none" stroke="#59f59b" stroke-width="2"/>',
        # Title
        f'<text x="{left}" y="44" font-family="Consolas, \'Courier New\', monospace" font-size="20" fill="#59f59b">{USERNAME}@github</text>',
        f'<text x="{left}" y="68" font-family="Consolas, \'Courier New\', monospace" font-size="14" fill="#484f58">{"─" * 28}</text>',
    ]

    for index, (label, value) in enumerate(LINES, start=1):
        y = top + index * 30
        delay = round(index * 0.08, 4)
        body.append(
            f'<g opacity="0" transform="translate(-12 0) scale(0.94)">'
            f'<text x="{left}" y="{y}" font-family="Consolas, \'Courier New\', monospace" font-size="16">'
            f'<tspan fill="#3fb950">{label}</tspan>'
            f'<tspan fill="#484f58"> : </tspan>'
            f'<tspan fill="#e6edf3">{value}</tspan>'
            f'</text>'
            f'<animate attributeName="opacity" values="0;1" dur="0.24s" begin="{delay}s" fill="freeze"/>'
            f'<animateTransform attributeName="transform" type="translate" values="-12 0;0 0" dur="0.24s" begin="{delay}s" fill="freeze"/>'
            f'<animateTransform attributeName="transform" type="scale" values="0.94 0.94;1 1" dur="0.24s" begin="{delay}s" fill="freeze" additive="sum"/>'
            '</g>'
        )

    # Color palette blocks (neofetch style)
    palette_y = 340
    colors_row1 = ["#484f58", "#ff7b72", "#3fb950", "#d2a8ff", "#58a6ff", "#f0883e", "#f778ba", "#ffa657"]
    colors_row2 = ["#6e7681", "#ffa198", "#56d364", "#d8b4fe", "#79c0ff", "#ffa657", "#ff9bce", "#ffc680"]
    block = 16
    gap = 4

    delay_palette = round((len(LINES) + 1) * 0.08, 4)
    body.append(
        f'<g opacity="0">'
        f'<animate attributeName="opacity" values="0;1" dur="0.3s" begin="{delay_palette}s" fill="freeze"/>'
    )
    for i, color in enumerate(colors_row1):
        body.append(f'  <rect x="{left + i * (block + gap)}" y="{palette_y}" width="{block}" height="{block}" rx="2" fill="{color}"/>')
    for i, color in enumerate(colors_row2):
        body.append(f'  <rect x="{left + i * (block + gap)}" y="{palette_y + block + gap}" width="{block}" height="{block}" rx="2" fill="{color}"/>')
    body.append('</g>')

    # Footer
    body.append(
        f'<text x="{left}" y="400" font-family="Consolas, \'Courier New\', monospace" font-size="12" fill="#484f58">generated by GitHub Actions + Python</text>'
    )

    body.append('</svg>')
    return "\n".join(body)


def main() -> int:
    OUTPUT.write_text(build_svg(), encoding="utf-8")
    print(f"Saved {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
